# Generated by Django 3.2.13 on 2022-06-25 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=11)),
                ('image', models.ImageField(upload_to='product-img/%Y/%m/%d/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50)),
                ('quentity', models.IntegerField()),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('total_qty', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=11)),
                ('is_placed', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='sales.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
